---
  - hosts: localhost
    gather_facts: no
    tasks:
      - name: Clone from template
        vmware_guest:
          hostname: "{{ vcenter_ip }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: False
          name: test_vm2
          template: tiny-template
          datacenter: Austin-Datacenter
          folder: /Austin-Datacenter/vm
          state: poweredon
          wait_for_ip_address: yes