---
  - hosts: localhost
    gather_facts: no
    tasks:
      - name: Clone from template
        vmware_guest:
          hostname: 10.150.1.6
          username: administrator@vsphere.local
          password: Hell0w0rld1!
          validate_certs: False
          name: test_vm2
          template: tiny-template
          datacenter: Austin-Datacenter
          folder: /Austin-Datacenter/vm/Austin-Datacenter/Billy
          state: poweredon
          wait_for_ip_address: yes