---
  - hosts: all
    gather_facts: no
    tasks:
      - name: Clone from template
        vmware_guest:
          hostname: "{{ vcenter_ip }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: False
          name: "{{ vm_name }}"
          template: "{{ vm_template }}"
          datacenter: Austin-Datacenter
          folder: /Austin-Datacenter/vm/{{ vm_folder }}
          state: poweredon
          wait_for_ip_address: no